# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/huezzo/Documents/LIESE/SDIO_Zynq_7020/hw/vivado_proj/zybo_sdio/zybo_sdio.srcs/sources_1/bd/zybo_sdio_bd/ip/zybo_sdio_bd_processing_system7_0_1/zybo_sdio_bd_processing_system7_0_1.xci
# IP: The module: 'zybo_sdio_bd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/huezzo/Documents/LIESE/SDIO_Zynq_7020/hw/vivado_proj/zybo_sdio/zybo_sdio.gen/sources_1/bd/zybo_sdio_bd/ip/zybo_sdio_bd_processing_system7_0_1/zybo_sdio_bd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_sdio_bd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/huezzo/Documents/LIESE/SDIO_Zynq_7020/hw/vivado_proj/zybo_sdio/zybo_sdio.srcs/sources_1/bd/zybo_sdio_bd/ip/zybo_sdio_bd_processing_system7_0_1/zybo_sdio_bd_processing_system7_0_1.xci
# IP: The module: 'zybo_sdio_bd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/huezzo/Documents/LIESE/SDIO_Zynq_7020/hw/vivado_proj/zybo_sdio/zybo_sdio.gen/sources_1/bd/zybo_sdio_bd/ip/zybo_sdio_bd_processing_system7_0_1/zybo_sdio_bd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_sdio_bd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
