# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_sdio_bd/zybo_sdio_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_sdio_bd || ORIG_REF_NAME==zybo_sdio_bd} -quiet] -quiet

# IP: bd/zybo_sdio_bd/ip/zybo_sdio_bd_processing_system7_0_1/zybo_sdio_bd_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_sdio_bd_processing_system7_0_1 || ORIG_REF_NAME==zybo_sdio_bd_processing_system7_0_1} -quiet] -quiet

# XDC: /home/huezzo/Documents/LIESE/SDIO_Zynq_7020/hw/vivado_proj/zybo_sdio/zybo_sdio.gen/sources_1/bd/zybo_sdio_bd/zybo_sdio_bd_ooc.xdc
